//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGisPlannerToolbox.WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SGDB1;Initial Catalog=MEDIACENTER;Integrated Security=True")]
        public string MEDIACENTERConnectionString {
            get {
                return ((string)(this["MEDIACENTERConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool activeMapViewFilter_FilterMediaDockWin {
            get {
                return ((bool)(this["activeMapViewFilter_FilterMediaDockWin"]));
            }
            set {
                this["activeMapViewFilter_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool slectionVisibility_FilterMediaDockWin {
            get {
                return ((bool)(this["slectionVisibility_FilterMediaDockWin"]));
            }
            set {
                this["slectionVisibility_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool issuesFromActiveView_FilterMediaDockWin {
            get {
                return ((bool)(this["issuesFromActiveView_FilterMediaDockWin"]));
            }
            set {
                this["issuesFromActiveView_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int zoomOption_FilterMediaDockWin {
            get {
                return ((int)(this["zoomOption_FilterMediaDockWin"]));
            }
            set {
                this["zoomOption_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showMediaWithDist_FilterMediaDockWin {
            get {
                return ((bool)(this["showMediaWithDist_FilterMediaDockWin"]));
            }
            set {
                this["showMediaWithDist_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collapsedMedia_FilterMediaDockWin {
            get {
                return ((bool)(this["collapsedMedia_FilterMediaDockWin"]));
            }
            set {
                this["collapsedMedia_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double transparencyVal_FilterMediaDockWin {
            get {
                return ((double)(this["transparencyVal_FilterMediaDockWin"]));
            }
            set {
                this["transparencyVal_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyNotDigitized_MediaDigitizerForm {
            get {
                return ((bool)(this["onlyNotDigitized_MediaDigitizerForm"]));
            }
            set {
                this["onlyNotDigitized_MediaDigitizerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fromMapView_onlyDigitized_MediaDigitizerForm {
            get {
                return ((bool)(this["fromMapView_onlyDigitized_MediaDigitizerForm"]));
            }
            set {
                this["fromMapView_onlyDigitized_MediaDigitizerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool selectionVisibility_AreaDigitizerForm {
            get {
                return ((bool)(this["selectionVisibility_AreaDigitizerForm"]));
            }
            set {
                this["selectionVisibility_AreaDigitizerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mediaAsGroup_FilterMediaDockWin {
            get {
                return ((bool)(this["mediaAsGroup_FilterMediaDockWin"]));
            }
            set {
                this["mediaAsGroup_FilterMediaDockWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color colorIndicator_PlanAdvertismementAreaWizard {
            get {
                return ((global::System.Drawing.Color)(this["colorIndicator_PlanAdvertismementAreaWizard"]));
            }
            set {
                this["colorIndicator_PlanAdvertismementAreaWizard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int planningLevel_PlanAdvertisementAreaWizard {
            get {
                return ((int)(this["planningLevel_PlanAdvertisementAreaWizard"]));
            }
            set {
                this["planningLevel_PlanAdvertisementAreaWizard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stillShowSystemDigitizedTours_MediaDigitizerForm {
            get {
                return ((bool)(this["stillShowSystemDigitizedTours_MediaDigitizerForm"]));
            }
            set {
                this["stillShowSystemDigitizedTours_MediaDigitizerForm"] = value;
            }
        }
    }
}
